stages:
    - build
    - deploy

# build stage
build_app:
    image: node:14
    stage: build
    only:
        - master
    script:
        - npm install
        - npm run build
    cache:
        paths:
            - node_modules/
    artifacts:
        paths:
            # build folder
            - dist/
        expire_in: 1 hour

production:
    image: node:14
    stage: deploy
    only:
        - master
    script:
        - 'curl --location --output artifacts.zip --header "PRIVATE-TOKEN: $PRIVATE_ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/kidsloopvn%2Fcurricula-guidelines/jobs/$CI_JOB_ID/artifacts/download"'
        - ls
        - 'unzip artifacts.zip /var/www/guidelines'
